name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scalafix
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Test
      run: sbt tests/test
    - name: Test report
      uses: dorny/test-reporter@v1.7.0
      if: always()
      with:
        name: MUnit tests
        path: '**/target/test-reports/*.xml'
        reporter: 'java-junit'

    - name: Style check
      if: success() || failure()
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

    - name: Sbt submit dependency
      uses: scalacenter/sbt-dependency-submission@v2.1.2

